resources:
  - name: git-sources
    type: git
    source:
      uri: https://github.com/bartem08/splitter.git
      username: ((git-username))
      password: ((git-password))
      branch: master
      skip_ssl_verification: true
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-username))
      password: ((cf-password))
      organization: artem-org
      space: DEV
      skip_cert_check: true

jobs:
  - name: test-build-publish
    plan:
      - get: git-sources
      - task: test and build
        file: git-sources/ci/userservice/tasks/test-and-build.yml
      - put: cf-dev
        params:
          manifest: git-sources/ci/userservice/manifests/manifest-dev.yml
          path: splitter-jars/*.jar
          environment_variables:
            SPRING_PROFILES_ACTIVE: dev



