---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: git-sources

outputs:
  - name: splitter-jars

caches:
  - path: .gradle/

run:
  path: git-sources/ci/app/tasks/test-and-build.sh